package com.quarkboom.smartcounter;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.quarkboom.smartcounter.CounterBean;

import com.quarkboom.smartcounter.CounterBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig counterBeanDaoConfig;

    private final CounterBeanDao counterBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        counterBeanDaoConfig = daoConfigMap.get(CounterBeanDao.class).clone();
        counterBeanDaoConfig.initIdentityScope(type);

        counterBeanDao = new CounterBeanDao(counterBeanDaoConfig, this);

        registerDao(CounterBean.class, counterBeanDao);
    }
    
    public void clear() {
        counterBeanDaoConfig.clearIdentityScope();
    }

    public CounterBeanDao getCounterBeanDao() {
        return counterBeanDao;
    }

}
